# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daily Oops!
email: yukaihuangtw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yukai's blog. Life, music, web, and all the fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yukaii.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Yukaii

permanlink: /blog/:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  # Prevent demo files to be included in the sitemap.xml

# Build settings
markdown: kramdown


kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

highlighter: rouge

gems:
  - jekyll-assets
  - uglifier
  - sass
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

# jekyll assets settings
assets:
  compress:
    css: sass
    js:  uglifier
  #
  autowrite: true
  prefix: "/assets"

  #
  sources:
    - _assets/css
    - _assets/img
    - _assets/js
    - _assets/fonts
  #

  features:
    liquid: true
