title: Daily Oops!
email: yukaihuangtw@gmail.com
description: >
  Yukai's blog. Web tech, apps, photos, and notes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yukaii.tw" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Yukaii
full_name: Yukai Huang
google_analytics: 'UA-49526118-7'

disqus:
  enabled: true
  short_name: dailyoops

collections:
  hi_tips:
    output: true
    permalink: /hi-tips/:path/

theme: octoflavor

# Build settings
markdown: redcarpet

redcarpet:
  extensions:
    - tables
    - strikethrough
    - highlight
    - footnotes
    - superscript
    - autolink
    - fenced_code_blocks
