title: Daily Oops!
email: yukaihuangtw@gmail.com
description: >
  Yukai's blog. Web tech, apps, photos, and notes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yukaii.tw" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Yukaii
full_name: Yukai Huang
google_analytics: 'UA-49526118-7'
default_post_collection: blog

disqus:
  enabled: true
  short_name: dailyoops

collections:
  hi_tips:
    output: true
    permalink: /hi-tips/:path/

permalink: /blog/:year/:month/:day/:title/

remote_theme: Yukaii/octoflavor
# uncomment theme when develop locally
# theme: octoflavor

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-octicons
  - jekyll-remote-theme

# Build settings
markdown: kramdown
kramdown:
  input: GFM
