# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Daily Oops!
email: yukaihuangtw@gmail.com
description: >
  Yukai's blog. Web tech, apps, photos, and notes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yukaii.tw" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  Yukaii
google_analytics: 'UA-49526118-7'

permalink: /blog/:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  # Prevent demo files to be included in the sitemap.xml

# Build settings
markdown: redcarpet

redcarpet:
  extensions:
    - tables
    - strikethrough
    - highlight
    - footnotes
    - superscript
    - autolink
    - fenced_code_blocks

collections:
  hi_tips:
    output: true
    permalink: /hi-tips/:path/

plugins:
  - jekyll-assets
  - uglifier
  - sass
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-octicons

# jekyll assets settings
assets:
  compress:
    css: sass
    js:  uglifier
  #
  autowrite: true
  prefix: "/assets"

  #
  sources:
    - _assets/css
    - _assets/img
    - _assets/js
    - _assets/fonts
  #

  features:
    liquid: true
